<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct();
 $_helper = $this->helper('Magento\Catalog\Helper\Output');
 $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                    ->init($_product, 'product_base_image')
                    ->constrainOnly(TRUE)
                    ->keepAspectRatio(TRUE)
                    ->keepTransparency(TRUE)
                    ->keepFrame(FALSE)
                    ->resize(800, 800)->getUrl();
?>

<div class="social-addthis" data-media="<?php echo $imageUrl ?>">
      <a href="https://api.addthis.com/oexchange/0.8/forward/facebook/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-facebook fa fa-facebook"></span>
      </a> 
      <a href="https://api.addthis.com/oexchange/0.8/forward/twitter/offer?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-twitter fa fa-twitter"></span>
      </a>
	 <a href="https://www.pinterest.com/pin/create/button/?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&media=<?php echo $imageUrl ?>&description=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank">
	      <span class="icon-pinterest fa fa-pinterest-square"></span>
      </a> 
	  <?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
       class="action"><span><i class="fa fa-envelope" aria-hidden="true"></i><?php /* @escapeNotVerified */ echo __('Email') ?></span></a>
<?php endif; ?>
</div> 


<!-----------Custom code start-----------call a block------> 
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('rk')->toHtml();?>
<!-----------Custom code end----------------->


<!-----------Custom code start----------------->

<!--iframe width="175" height="40" src="https://w2.countingdownto.com/3843877" frameborder="0"--><!--/iframe-->

<!--div class="powr-countdown-timer" id="31947b9b_1632510439"></div><script src="https://www.powr.io/powr.js?platform=html"--><!--/script-->

<style>
.swatch-attribute-label { z-index: 99999;}
.swatch-option-tooltip {
	display:none !important;
  visibility:hidden !important;
    max-width: 0px !important;
    max-height: 0px !important;
    overflow:hidden;
    min-height: 0px !important;
    min-width: 0px !important; border:none !important;
    background:transparent !important; 
}
</style>

<!-----------Custom code end----------------->

